[options]
db_name = yyy
admin_passwd = admin
data_dir = /var/lib/odoo
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
proxy_mode = True
addons_path = /mnt/extra-addons/cml_addons,/mnt/extra-addons/addons,/mnt/extra-addons/ph_payroll,/mnt/extra-addons/submodule/OpenHRMS,/mnt/extra-addons/submodule/account-invoicing,/mnt/extra-addons/submodule/commission,/mnt/extra-addons/submodule/muk_misc,/mnt/extra-addons/submodule/muk_web,/mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons
