[options]

admin_passwd = admin
data_dir = /var/lib/odoo
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
proxy_mode = False
addons_path = /opt/odoo12/custom/cml_addons,/opt/odoo12/custom/addons,/opt/odoo12/custom/ph_payroll,/opt/odoo12/custom/submodule/OpenHRMS,/opt/odoo12/custom/submodule/account-invoicing,/opt/odoo12/custom/submodule/commission,/opt/odoo12/custom/submodule/muk_misc,/opt/odoo12/custom/submodule/muk_web,/opt/odoo12/custom/submodule/aeroo_reports,/opt/odoo12/custom/submodule/muk_base,/opt/odoo12/custom/submodule/odooapps,/opt/odoo12/custom/submodule/partner-contact,/opt/odoo12/custom/submodule/server-tools,/opt/odoo12/custom/submodule/server-ux,/opt/odoo12/custom/submodule/CybroAddons,/opt/odoo12/custom/submodule/account-analytic,/opt/odoo12/custom/submodule/contract,/opt/odoo12/custom/submodule/hr,/opt/odoo12/custom/submodule/maintenance,/opt/odoo12/custom/submodule/manufacture,/opt/odoo12/custom/submodule/muk_website,/opt/odoo12/custom/submodule/purchase-workflow,/opt/odoo12/custom/submodule/sale-workflow,/opt/odoo12/custom/submodule/stock-logistics-workflow,/opt/odoo12/custom/submodule/SerpentCS_Contributions,/usr/lib/python3/dist-packages/odoo/addons
