from . import hr
from . import fleet
from . import product
from . import scrap
from . import purchase
from . import overtime
from . import hr_expense
from . import rma
from . import mrp_production_inherit
from . import hr_warning_inherit
from . import account_invoice_inherit
from . import res_partner
from . import sale
