from . import abstract_hr_overtime_request
from . import hr_overtime_request_single
from . import hr_overtime_line
from . import hr_contract
from . import hr_payslip_overtime_line
from . import hr_payslip
from . import hr_overtime_rule
from . import hr_overtime_rule_code
from . import resource_calendar
from . import hr_employee
from . import hr_overtime_reason
