{
    'name': 'PH Payroll Computation',
    'version': '12.0.3',
    'summary': 'Payroll Register, Payslips, Payroll Period, etc',
    'category': 'Generic Modules/Human Resources',
    'author': 'Cybrosys Technologies Pvt. Ltd., Allan J. Manuel',
    'depends': ['hr_payroll', 'hr_payroll_account', 'ph_payroll_contract', 'ph_payroll_loan'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'views/contribution_tax.xml',
        'views/payroll_period.xml',
        'views/payroll.xml',
        'views/holiday.xml',
        'views/work_schedule.xml',
        'views/loan.xml',
        'data/data.xml',
        'data/department.xml',
        'data/payroll_adjustment.xml',
        'data/contribution_tax.xml',
        'data/rice_allowance_computation.xml',
        'reports/work_schedule.xml',
        'reports/payslip.xml',
        'aeroo/reports.xml',
    ],
    'demo': [],
    'license': 'AGPL-3',
    'installable': True,
    'application': True,
    'auto_install': False,
}
