{
    'name': 'PH Payroll Core',
    'version': '12.0.3',
    'summary': """PH Payroll Suit: It brings all PH Payroll modules""",
    'description': 'Main module of PH Payroll. It brings all others into a single module',
    'category': 'Generic Modules/Human Resources',
    'author': 'Cybrosys Technologies Pvt. Ltd., Allan J. Manuel',
    'depends': [
        'base',
        'mail',
        'account',
        'contacts',
        'hr_payroll',
        'hr_gamification',
        'hr_recruitment',
        'hr_attendance',
        'hr_expense',
        'hr_timesheet',
        'report_aeroo',
        'ph_payroll_employee',
        'ph_payroll_contract',
        'ph_payroll_leave',
        'ph_payroll_loan',
        'ph_payroll_overtime',
        'ph_payroll_attendance',
        'ph_payroll_computation',
        'ph_payroll_appraisal',
        'ph_payroll_employee_documents',
        'ph_payroll_reward_warning',
        'ph_payroll_custody',
        'ph_payroll_biometric_machine'
    ],
    'data': [
        'views/menu_arrangement_view.xml',
        'views/hr_config_view.xml',
	    'views/template_view.xml',
    ],
    'demo': [],
    'images': ['static/description/banner.gif'],
    'qweb': ['static/src/xml/*.xml'],
    'license': 'AGPL-3',
    'installable': True,
    'auto_install': False,
    'application': True,
}
