services:
  web:
    build: .
    image: odoo12-py37
    container_name: odoo-web
    ports:
      - "8069:8069"
    environment:
      - VIRTUAL_HOST=yyy-staging.on-cloud.io
      - VIRTUAL_PORT=8069
      - LETSENCRYPT_HOST=yyy-staging.on-cloud.io
      - LETSENCRYPT_EMAIL=renato@cml-intl.com
      - HOST=False
      - USER=odoo
      - PASSWORD=2bund2nc3+
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/opt/odoo12/custom
      - /var/run/postgresql:/var/run/postgresql
    networks:
      - nginx-proxy-network
    restart: always

volumes:
  odoo-web-data:

networks:
  nginx-proxy-network:
    external: true
